compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - checksum: f5005afc41a9f40f3590e59f6dd35d6e7c982306549d95408247b4ddbcdc82542498558053e016a7f54f76ba6c5d80ec4114f25dd8ee8f1dd6fe12b801fd0d7c
    path: .yarn/plugins/@yarnpkg/plugin-cyclonedx.cjs
    spec: .yarn/plugins/@yarnpkg/plugin-cyclonedx.cjs

yarnPath: .yarn/releases/yarn-4.2.2.cjs
