/*
 * Copyright (C) 2007-2019 Crafter Software Corporation. All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

CStudioAuthoring.Messages.registerBundle("siteDashboard", "en", {
    dashboardTitle: "Dashboard",

    dashboardCollapseAll: "Collapse All",
    dashboardExpandAll: "Expand All",
    dashboardEdit: "Edit",

    approvedScheduledCollapseAll: "Collapse All",

    dashletFilterPages: "Pages",
    dashletFilterComponents: "Components",
    dashletFilterDocuments: "Documents",
    dashletFilterAssets: "Assets",
    dashletFilterAll: "All",

    dashletGoLiveQueueTitle: "Items Waiting For Approval",
    dashletGoLiveCollapseAll: "Collapse All",
    dashletGoLiveExpandAll: "Expand All",
    dashletGoLiveShowInProgress: "Show \"In-Progress\" Items",
    dashletGoLiveHideInProgress: "Hide \"In-Progress\" Items",
    dashletGoLiveColPageName: "Item Name",
    dashletGoLiveColEdit: "Edit",
    dashletGoLiveColURL: "URL",
    dashletGoLiveColEnvironment: "Environment",
    dashletGoLiveColPublishDate: "Publish Date",
    dashletGoLiveColLastEditedBy: "Last Edited By",
    dashletGoLiveColLastEditedDate: "Last Edited",
    dashletGoLivePages: "Pages ({0})",
    dashletGoLiveComponents: "Components ({0})",
    dashletGoLiveAssets: "Assets ({0})",
    dashletGoLiveEdit: "Edit",

    dashletApprovedSchedTitle: "Approved Scheduled Items",
    dashletApprovedSchedCollapseAll: "Collapse All",
    dashletApprovedSchedExpandAll: "Expand All",
    dashletApprovedSchedShow: "Show",
    dashletApprovedSchedColGoLiveDate: "Go Live Date",
    dashletApprovedSchedColEdit: "Edit",
    dashletApprovedSchedColURL: "URL",
    dashletApprovedSchedColEnvironment: "Environment",
    dashletApprovedSchedColPackageId: "Package Id",
    dashletApprovedSchedColLastEdited: "Last Edited",
    dashletApprovedSchedFilterPages: "Pages",
    dashletApprovedSchedFilterComponents: "Components",
    dashletApprovedSchedFilterDocuments: "Documents",
    dashletApprovedSchedFilterAll: "All",

    showNumItems: "Show",

    dashletRecentDeployTitle: "Recently Published",
    dashletRecentDeployCollapseAll: "Collapse All",
    dashletRecentDeployExpandAll: "Expand All",
    dashletRecentDeployShow: "Show",
    dashletRecentDeployColMadeLiveDateDate: "Publish Date",
    dashletRecentDeployColEdit: "Edit",
    dashletRecentDeployColURL: "URL",
    dashletRecentDeployColEndpoint: "Environment",
    dashletRecentDeployColDeployBy: "Published By",
    dashletRecentDeployColLastEdited: "Last Edited",
    dashletRecentDeployColPageName: "Item Name",

    dashletMyRecentActivityTitle: "My Recent Activity",
    dashletMyRecentActivityCollapseAll: "Collapse All",
    dashletMyRecentActivityExpandAll: "Expand All",
    dashletMyRecentActivityHideLiveItems: "Hide Live Items",
    dashletMyRecentActivityShowLiveItems: "Show Live Items",
    ddashletMyRecentActivityShow: "Show",
    dashletMyRecentActivityColPageName: "Item Name",
    dashletMyRecentActivityColEdit: "Edit",
    dashletMyRecentActivityColURL: "URL",
    dashletMyRecentActivityColPublishDate: "Publish Date",
    dashletMyRecentActivityColLastEditedBy: "Last Edited By",
    dashletMyRecentActivityColMyLastEdit: "My Last Edit",

    dashletIconGuideTitle: "Icon Guide",
    dashletWorkflowStatesTitle: "Workflow States",
    dashletItemTypesTitle: "Item Types",
    dashletIconGuideNavigationPage: "Navigation Page",
    dashletIconGuideFloatingPage: "Floating Page",
    dashletIconGuideComponent: "Component",
    dashletIconGuideDocument: "Document",
    dashletIconGuideStateNew: "Never Published",
    dashletIconGuideStateDisabled: "Disabled",
    dashletIconGuideStateDeleted: "Deleted",
    dashletIconGuideStateInProgress: "Edited",
    dashletIconGuideStateInWorkflow: "In Workflow",
    dashletIconGuideStateScheduled: "Scheduled",
    dashletIconGuideStateSystemProcessing: "Processing",
    dashletIconGuideStateLocked: "Locked for Editing",
    dashletIconGuideTemplateScript: "Template or Script",
    dashletIconGuideTaxonomy: "Taxonomy",
    dashletIconGuideImage: "Image",
    dashletIconGuideVideo: "Video",
    dashletIconGuideCss: "CSS",
    dashletIconGuideFont: "Font",
    dashletIconGuidePdf: "PDF",
    dashletIconGuidePowerPoint: "MS PowerPoint",
    dashletIconGuideWord: "MS Word",
    dashletIconGuideExcel: "MS Excel",
    dashletIconGuideZip: "Zip",
    dashletIconGuideGroovy: "Groovy",
    dashletIconGuideOtherFiles: "Other Files"

});

CStudioAuthoring.Messages.registerBundle("contextnav", "en", {
    siteContent: "Site Content",
    sideBar: "Sidebar",

    wcmContentEdit: "Edit",
    wcmContentView: "View",
    wcmContentSubmit: "Request Publish",
    wcmContentDependencies: "Dependencies",
    wcmContentDelete: "Delete",
    wcmContentSubmitDelete: "Request Delete",
    wcmContentReject: "Reject",
    wcmContentSchedule: "Schedule",
    wcmContentApprove: "Approve & Publish",
    wcmContentDuplicate: "Duplicate",
    wcmContentHistory: "History",
    wcmContentPageDisabled: "This content is disabled",
    wcmContentSavedAsDraft: "Content was saved as DRAFT. Some required fields may not be populated. This can cause errors when previewed or deployed.",

    InProgress: "Edited",
    Deleted: "Deleted",
    SubmittedforDelete: "Submitted for Delete",
    mixedStates: "Items (Mixed States)",
    Submitted: "Submitted for Publish",
    Live: "Live",
    Scheduled: "Scheduled",

    search: "Search",

    logout: "Log Out",
    close: "Close",

    variableLabel: "Template code examples",

    networkError: "Network Error. Some functionality may be unavailable.",

    notification: "Notification",
    noEventError: "No event handler associated.",

    publishStatus: "Publish Status",
    idle: "Idle",
    busy: "Busy",
    stopped: "Stopped"

});

CStudioAuthoring.Messages.registerBundle("previewTools", "en", {
    previewToolsTitle: "Preview Tools",
    inContextEditing: "In-Context Editing",
    pageComponents: "Page Components",
    responsivePreview: "Responsive Preview",
    desktop: "Desktop",
    browser: "Browser",
    iphone: "iPhone5iPhone5S",
    iPad: "iPad",
    targeting: "Targeting",
    translation: "Translation",
    inContextEditOn: "In-Context Edit On",
    inContextEditOff: "In-Context Edit Off",
    publishingChannel: "Publishing Channel",
    web: "Web",
    smartPhone: "Smart Phone",
    tablet: "Tablet",
    multiVariantTesting: "Multi-Variant Testing",
    YellowVsBlue: "Yellow vs Blue Mask on Home",
    yellow: "Yellow",
    blue: "Blue",
    FacetedVsKeyword: "Faceted Search vs Keyword",
    faceted: "Faceted",
    facetedKeyword: "Faceted + Keyword",
    keywordOnly: "Keyword Only",
    HomeRedVsBlue: "Home Red vs Blue CTA Buttons",
    red: "Red",
    catalogPageSorting: "Catalog Page Sorting",
    arrivalDate: "Arrival Date",
    priceHightoLow: "Price High to Low",
    priceLowtoHigh: "Price Low to High",
    editTemplate: "Edit Template",
    editController: "Edit Controller",
    jumpToRegion: "Jump to Region",
    dimensionsPx: "Dimensions (px)",
    viewPortSize: "Viewport Size (px)",
    presets: "Presets",
    custom: "Custom",
    addComponent: "Add Component",
    done: "Done",
    general: "General",
    components: "Components",
    persona: "Persona",
    properties: "Properties",
    assume: "Assume",
    update: "Update",
    active: "Active",
    reportsOff: "Reports Off",
    reportsError: "Unable to render report due to error",
    addComponent :"Add Component",
    done: "done",
    components: "Components",
    general: "General",
    text: "text",

    //login
    login: "Login",
    emailUsername: "Email/Username",
    password : "Password",
    signIn: "Sign in",
    signBackIn: "Sign back in",
    signInContinueWorking: "Sign in to continue working",
    sessionExpireInactivity: "Your session has expired due to inactivity",
    doneSignOut:"I'm done, signout",

    search: "Search",
    publishingStatus: "Publishing Status",
    users: "Users",
    sites: "Sites",
    help: "Help",
    documentation: "Documentation",
    about: "About",
    settings: "Settings",
    signOut: "Sign Out"

});

CStudioAuthoring.Messages.registerBundle("siteDropdown", "en", {
    pages: "Pages",
    Pages: "Pages",
    page: "Page",
    components: "Components",
    Components: "Components",
    component: "Component",
    classes: "Classes",
    staticassets: "Static Assets",
    templates: "Templates",
    scripts: "Scripts",
    adminConsole: "Admin Console",
    siteconfig: "Site Config",
    previewSync: "Preview Sync",
    syncrepo: "Sync From Repository",
    allSites: "All Sites",
    dashboard: "Dashboard",
    newContent: "New Content",
    newFolder: "New Folder",
    upload: "Upload",
    edit: "Edit",
    view: "View",
    changeTemplate: "Change Template",
    delete: "Delete",
    cut: "Cut",
    copy: "Copy",
    paste: "Paste",
    duplicate: "Duplicate",
    history: "History",
    unlock: "Unlock",
    noActionsAvailable: "No Actions Available",
    createFolder: "Create Folder",
    renameFolder: "Rename Folder",
    createTemplate: "Create Template",
    templateFilename: "Provide a filename for the template",
    folderName: "Provide a new foldername",
    createController: "Create Controller",
    controllerFilename: "Provide a filename for the script",
    bulkUploadAssets: "Bulk Upload Assets",
    lastEdited: "Last Edited",
    editedBy: "Edited by",
    lockedBy: "Locked by",
    status: "Status",
    scheduled: "Scheduled",
    loading: "Loading...",

    /*tooltip-Status*/
    statusDeleted: "Deleted",
    statusScheduledForDelete: "Scheduled for Delete",
    statusSubmittedForDelete: "Submitted for Delete",
    statusAndDisabled: "and Disabled",
    statusProcessing: "Processing",
    statusInProgress: "Edited",
    statusLive: "Live",
    statusAnd: "and",
    statusSubmitted: "In Workflow",
    statusScheduled: "Scheduled",
    statusDisabled: "Disabled",
    wcmContentSubmit: "Request Publish",
    wcmContentApprove: "Approve & Publish",

    notification: "Notification",
    previewInitiated: "Preview server synch-all initiated.",
    syncfromRepoInitiated: "Synchronization from Repository initiated.",

    lookUpItemError: "Unable to look up item. Please contact your system administrator.",
    pathSameError: "Source and destination path are same.",
    pageExistError: "Page already exist at the destination.",
    wcmContentDependencies: "Dependencies",
    wcmContentApprove: "Approve & Publish",

    create: "Create",
    rename: "Rename",
    cancel: "Cancel"

});

CStudioAuthoring.Messages.registerBundle("forms", "en", {
    new:"New",
    expandAll: "Expand All",
    collapseAll: "Collapse All",
    pageName: "Item Name",
    location: "Location",
    sectionValidation: "{0} of {1} field requirements are invalid",
    saveAndClose: "Save and Close",
    saveAndCloseDraft: "Save Draft",
    saveAndPreview: "Save and Preview",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    repeatAddAnother: "Add Another",
    repeatMoveUp: "Move Up",
    repeatMoveDown: "Move Down",
    repeatDelete: "Delete",
    errMissingRequirements: "You cannot save until all form requirements are satisfied",
    errSaveFailed: "Unable to save form content. Please try again or contact or your system administrator.",
    errOnRepeat: "Error on repeater operation: {0}",
    errFailedToLoadContent: "Error loading content: {0}",
    errExpectedIndexXml: "Not expecting file-name other than index.xml",
    ok: "Ok",
    yes: "Yes",
    no: "No",
    submit:"Submit",
    loading:"Loading&hellip;",
    viewSample: "View Sample",
    hideSample: "Hide Sample",
    clearCache: "Clear Cache",
    continueEditing: "Continue Editing",
    notification: "Notification",
    previewLoaded : "Preview Loaded.",

    copy: "Copy",
    copyDescription: "Please select any of the sub-pages you would like to batch copy.<br/> When pasting, any selected sub-pages and their positional heirarchy will be retained.",
    page: "Page",
    loadingContents: "Loading items...",
    cut: "Cut",
    cutDescription: "Please select any of the sub-pages you would like to batch cut.<br/> When pasting, any selected sub-pages and their positional heirarchy will be retained.",

    create: "Create",
    newFolderTitle: "Create a New Folder",
    newFolderBody: "Please enter a folder name",
    newFolderLabel: "Folder Name:",
    newFolderUpdating: "Creating a folder...",

    chooseContentType: "Choose Content Type",
    chooseContentTypeBody: "The following starter templates are available for use within this section.",
    chooseContentTypeLabel: "Template Name:",
    chooseContentTypePreview: "Preview:",

    cancelDialogHeader:"Crafter Studio",
    cancelDialogBody:"Close this form without saving changes?",
    noContentTypes:"No content types available for content at path:",
    noTemplatesAssoc:"No template associated for page:",
    noTemplateAssocAdm:"There is no template associated with this content type. Click Save to proceed with save operation or Continue to update the content type (under Basic Content Type Properties) with a template.",

    changeTemplateDialogTitle:"Warning: Change Content Type",
    changeTemplateDialogSubTitle:"Crafter Studio",
    changeTemplateDialogBody:"The following operation may result in data loss. Would you like to proceed?",
    
    bulkPublishDialogTitle:"Warning: Bulk Publish",
    bulkPublishDialogBody:"Bulk publish will force publish all items that match the pattern requested including their dependencies.</br> Please make sure that all modified items (including potentially someone's work in progress) are ready to </br> be published before continuing.",
    bulkPublish: "Bulk Publish",
    bulkPublishPathToPublish: "Path to Publish",
    bulkPublishPublishingEnv: "Publishing Environment",
    bulkPublishPublish: "Publish",

    historyDialogTitle: "Version History",
    historyDialogSubTitle: "History shown for:",
    historyDialogTableRowVersion: "Version Date and Time",
    historyDialogTableRowTime: "Edit Time",
    historyDialogTableRowEditBy: "Edited By",
    historyDialogTableRowComment: "Comment",
    historyDialogTableRowActions: "Actions",
    historyDialogRevert: "Revert",
    historyDialogLoadingWait: "Loading, please wait&hellip;",
    historyDialogNoVersionsFound: "No versions found.",
    historyDialogUnable:"Unable to load version history.",
    historyDialogTryAgain:"Try again",
    historyDialogViewFileMessage:"View this version",
    historyDialogCompareFileMessage:"Compare to current",
    historyDialogRevertFileMessage:"Revert to this version",
    historyDialogCompare: "Compare",

    deleteDialogTitle: "Delete",
    deleteDialogSubTitle: "The following checked items will be deleted:",
    deleteDialogSetLink: 'Set everything to "Now"',
    deleteDialogPage: "Page",
    deleteDialogDelete: "Delete",
    deleteDialogNow: "Now",
    deleteDialogFeedBack: "Dependencies must be checked before you can submit",
    deleteDialogNoItemsSelected: "No items selected",
    deletedTitle: "Selection Deleted",
    deletedMessage: "The selection is being deleted and will be removed shortly.",

    deleteSubmitDialogTitle: "Submit for deletion",
    deleteSubmitDialogTime: "When would you like the checked item(s) to be deleted?",
    deleteSubmitEmailMe: "Email me when my items are deleted",
    deleteSubmitDialogAsSoon: "As soon as possible.",

    approveDialogTitle: "Approve for Publish",
    approveDialogSubTitle: "The following checked items will go live.",
    approveDialogWarning:"WARNING: The items you have selected for approval were submitted with different requested publish dates/times.",
    dependenciesDialogTitle: "Dependencies",
    dependenciesDialogSubTitle: "Dependencies shown for:",
    dependsOn: "Refers to this item",
    dependsOnMe: "Is referenced by this item",
    selectDeps: "Show content that:",
    dependenciesDialogItem: "Item",
    approveDialogPage: "Page",
    approveDialogOriginalSchedule: "Original Schedule",
    approveDialogSubmissionComment: "Submission Comment",
    approveDialogSelectedScheduling: "Selected Item Scheduling",
    approveDialogItemsLiveNow: "Items should go live now.",
    approveDialogItemsLiveDate: "Items go live on a specific date &amp; time",
    approveDialogPublishContent: "Publish Content",
    approveDialogPublishingOptions: "Publishing Options",
    approveDialogBroadcastUpdate: "Broadcast content update",

    requestApproveDialogTitle: "Request Publish",
    requestApproveDialogSubTitle: "When would you like the checked item(s) to go live?",
    requestApproveDialogEmailMe: "Email me when items are approved for publish.",

    newContTypeDialogTitle: "Create Content Type",
    newContTypeDialogDisplayLabel: "Display Label",
    newContTypeDialogContentTypeName: "Content Type Name",
    newContTypeDialogType: "Type",
    component: "Component",
    newContTypeDialogLabelMsg: "Provide a display label for this content type",
    newContTypeDialogContentTypeNamelMsg: "Provide a system name for this content type",
    newContTypeDialogTypeMsg: "Select the type for this content type",

    adminHelpDialogTitle: "Field Content",

    adminKeyValDialogTitle: "Values",
    adminKeyValDialogKey: "Key",
    adminKeyValDialogValue: "Value",
    addAnother: "Add Another",

    supportedChannelsDialogLabel: "Label",
    supportedChannelsDialogName: "Name",
    supportedChannelsDialogSize :"Size",

    setStatedDialogTitle: "Select States",
    setStatedDialogSetStates: "Set States",
    setStatedDialogSystemProcessing: "System Processing",

    setQueueDialogTitle: "Select States",
    setDeploymentQueue: "Deployment Queue",
    setDeploymentEndpoints: "Deployment Endpoints",
    setDeploymentJobs: "Deployment Jobs",
    setQueueDialogCancelDeployment: "Cancel Deployment",
    setQueueDialogSystemProcessing: "System Processing",

    deploymentTabSelectEndpoint: "Select Endpoint",
    deploymentTabEndpointProperty: "Property",
    deploymentTabEndpointValue: "Value",

    currentPage: "Current Page",

    wcmContentSavedAsDraft: "Content was saved as DRAFT. Some required fields may not be populated. This can cause errors when previewed or deployed.",

    previewInitiated: "Preview server synch-all initiated.",
    synchronizationRepo: "Synchronization from Repository initiated.",

    /*Preview*/
    previewToolsTitle: "Preview Tools",
    inContextEditing: "In-Context Editing",
    pageComponents: "Page Components",
    publishingChannel: "Publishing Channel",
    inContextEdit: "In-Context Edit",

    /*Error*/
    legacyFormNoSupported: "legacy form server no longer supported.",
    loadContentsError: "Unable to load contents. Please close the dialogue window and try again.",
    taxonomyError: "No taxonomy types available for",
    getDomainNameError: "Service.getDomainName depricated.",
    changeContTypeError: "Error changing Content Type.",
    notImplemented: "Not Implemented.",
    timeFormatError: "is not a valid time format, please provide a valid time.",
    localStoreExceeded: "Your local Storage Quota exceeded.",
    invalidFormat: "Is not a valid time format, please provide a valid time",
    addMoreItemsError: "You can't add more items, Remove one and try again.",
    imgReq: "Image description is required.",
    datasourceNotImageManager: "The configured datasource is not an image manager.",
    noDatasourceAssociated:"No datasource has been associated with this editor.",
    notAComponent: " is not a component or does not have items.",
    unableLoad: "The system was unable to load ",
    failure: "Failure.",
    loadFormDefError: "Failed to load form definition.",
    loadModelError: "Failed to load model.",
    controllerError: "No controller found.",
    notExist:" does not exist.",
    translationSubmitted: "Translation submitted.",
    numberPerPage: "Enter a number in show item per page.",
    revertError: "Revert failed.",
    legacyError: "legacy form server is no longer supported",
    contentTypesEmpty: "There are no content types available that can be created at the configured path.",
    componentCategoriesError: "There are no categories available that can be created."
});

CStudioAuthoring.Messages.registerBundle("search", "en", {
    defaultTitle: "Search",
    searchButtonLabel: "Search",
    keywordsLabel: "Keywords",
    searchResults: "Search Results",
    showing: "(Showing {0}-{1} of {2})",
    hideDescriptions: "Hide Descriptions",
    showDescriptions: "Show Descriptions",
    show: "Show",
    sort: "Sort",
    sortRelevance: "Relevance",
    sortAlphabetical: "Alphabetical",
    sortCreateDate: "Create Date",
    pagePrevious: "Previous",
    pageNext: "Next",
    resultsEdited: "Edited",
    resultsBy: "By",
    resultsUnknownType: "Unknown Type",
    resultsTemplate: "Template",
    errSearchFailed: "Search Failed. Try adjusting your filters. Cause: If issue persists contact administrator with error: {0}",
    errNoResults: "No results found.",
    zeroResults: "(0 results)"
});

CStudioAuthoring.Messages.registerBundle("browse", "en", {
    labelUrl: "URL",
    labelType: "Type",
    labelAddClose: "Add & Close",
    labelAddLink: "Add Link",
    labelClone: "Clone",
    selectAll: "Select All",
    clearAll: "Clear Selection",
    uploadLabel: "Upload",
    notification: "Notification",
    lookUpChildError : "Unable to lookup child form callback for search: ",
    lookUpParentError : "Unable to lookup parent context for search: ",
    loading: "Loading",
    serverError: "Server Error",
    noBrowseResults: "There are no files at this path.",
    noSearchResults: "There are no results.",
    showMore: "Show More",
    400: "Invalid CMIS parameter(s). Invalid CMIS data source configuration (hostname, port number, etc.), please contact your site administrator.",
    401: "CMIS Unauthorized: Invalid username or password in CMIS data source configuration, please contact your site administrator.",
    404: "CMIS Path Not Found.",
    408: "CMIS Timeout.",
    500: "Internal server error.",
    503: "CMIS Unavailable."
}); 

CStudioAuthoring.Messages.registerBundle("contentTypes", "en", {
    contenttypes: "Content Types",
    bulkoperations: "Bulk Operations",
    workflowjobs: "Workflow Jobs",
    workflowstates: "Workflow States",
    logginglevels: "Logging Levels",
    logconsole: "Log Console",
    publishing: "Publishing",
    status: "Status",
    audit: "Audit",
    groups: "Groups",
    contentTypes: "Content Types",
    configuration: "Configuration",
    workflowJobs: "Workflow Jobs",
    workflowStates: "Workflow States",
    loggingLevels: "Logging Levels",
    logConsole: "Log Console",
    previewsync: "Preview Sync",
    syncfromrepository: "Sync From Repository",
    deploymentQueues: "Deployment Queues",
    label: "Content Types",
    openExistingType: "Open Existing Type",
    createNewType: "Create New Type",
    save: "Save",
    cancel: "Cancel",
    create: "Create",
    close: "Close",
    saved: "Saved",
    clearVal: "Clear Value",
    saveFailed: "Save Failed",
    formSection: "Form Section",
    repeatingGroup: "Repeating Group",
    minOccurs: "Minimum Occurances",
    maxOccurs: "Maximum Occurances",
    formBasics: "Form Basics",
    formTitle: "Title",
    description: "Description",
    objectType: "Object Type",
    contentType: "Content Type",
    datasourceBasics: "Data Source Basics",
    title: "Title",
    name: "Name",
    properties: "Properties",
    sectionBasics: "Section Basics",
    variableName: "Name / Variable Name",
    iceGroup: "ICE Group",
    fieldBasics: "Field Basics",
    defaultValue: "Default Value",
    help: "Help",
    constraints: "Constraints",
    propertiesExplorer: "Properties Explorer",
    controls: "Controls",
    datasources: "Data Sources",
    defaultOpen: "Default Open",
    showInNav: "Show In Nav",
    descriptorMapper: "Descriptor Mapper",
    previewImage: "Preview Image ",
    config: "Configuration",
    controller: "Controller",

    warning: "Warning",
    warningBody: "Changing this value may result in broken links.",
    warningViewDeps: "To view the possible broken elements click ",
    warningLink: "here",

    notification: "Notification",
    deploymentCanceled: "Deployment items canceled.",

    createTemplate: "Create Template",
    templateFilename: "Provide a filename for the template",

    /*Controls*/
    textArea: "Text Area",
    linkTextarea:"Link Text Area",
    richTextEditor: "Rich Text Editor",
    input: "Input",
    uuid: "UUID",
    linkInput:"Link Input",
    dropdown: "Dropdown",
    linkedDropdown:"Linked Dropdown",
    dateTime: "Date / Time",
    checkBox: "Check Box",
    groupedCheckboxes: "Grouped Checkboxes",
    itemSelector: "Item Selector",
    image: "Image",
    video: "Video",
    label: "Label",
    pageOrder: "Page Order",
    fileName: "File Name",
    autoFilename: "Auto Filename",
    forceHTTPS: "Force HTTPS",
    disabled: "Disabled",
    flash: "Flash",
    internalName: "Internal Name",
    basicContentTypeProp: "Basic Content Type Properties",
    publishStarted:"Publish process has been started.",

    /*Datasources */
    childContent: "Child Content",
    imageUploadedDesktop: "Image Uploaded From Desktop",
    WebDAVUploadImage: "Image Uploaded to WebDav Repository",
    WebDAVUploadVideo: "Video Uploaded to WebDav Repository",
    imageWebDavRepository:"Image From WebDav Repository",
    videoWebDavRepository:"Video From WebDav Repository",
    fileWebDavRepository:"File From WebDav Repository",
    fileUploadedWebDavRepository:"File Uploaded to WebDav Repository",
    DAMImage: "DAM Image Flickr",
    fileUploadedDesktop: "File Uploaded From Desktop",
    flashUploadedDesktop: "Flash Uploaded from Desktop",
    videoUploadedDesktop: "Video Uploaded From Desktop",
    videoBrowse: "Video From Repository",
    videoCMISRepository:"Video From CMIS Repository",
    staticKeyValuePairs: "Static Key Value Pairs",
    configuredListOfPairs: "Configured List of Pairs",
    siteComponent: "Site Component",
    fileBrowse: "File Browse",
    hubspotForms: "Hubspot Forms",
    imageFromRepository: "Image From Repository",
    imageFromCMISRepository: "Image From CMIS Repository",
    CMISRepository: "CMIS Repository",
    salesforceCampaigns: "Salesforce Campaigns",
    treeContent: "Tree content",

    /*Properties*/
    size: "Size",
    maxLength: "Max Length",
    width: "Width",
    height: "Height",
    allowResize: "Allow Resize",
    forceRootBlockP: "Force Root Block p Tag",
    forcePNewLines: "Force p tags New Lines",
    forceBRNewLines: "Force br New Lines",
    requireImageAlt: "Require Image Alt Tag",
    supportedChannels: "Supported Channels",
    RTEConfiguration: "RTE Configuration",
    imageManager: "Image Manager",
    showDate: "Show Date",
    showTime: "Show Time",
    showClear: "Show Clear Value",
    setNowLink: "Set Now Link",
    populated: "Populated",
    allowPastDate: "Allow Past Date",
    populateExpression:"Populate Expression",
    useCustomTimezone: "Use Custom Timezone",
    readonly: "Readonly",
    readonlyOnEdit: "Readonly on Edit",
    datasource: "Data Source",
    showSelectAll: 'Show "Select All"',
    allowEmptyValue: "Allow Empty Value",
    thumbnailWidth: "Thumbnail Width",
    thumbnailHeight: "Thumbnail Height",
    displaySize: "Display Size",
    text: "Text",
    minSize: "Min Size",
    maxSize: "Max Size",
    itemManager: "Item Manager",
    disableFlatteningSearch: "Disable Flattening for Search",
    singleValueFilename: "Use single value filename (backward compat)",
    columns: "Columns",
    rows: "Rows",
    dataType: "Data Type",
    listName: "List Name",
    repositoryPath: "Repository Path",
    studioPath: "Studio Path",
    repositoryId: "Repository ID",
    browsePath: "Browse Path",
    allowedOperations: "Allowed Operations",
    clone: "Clone",
    link: "Link",
    cloneAndLink: "Clone and Link",
    string: "String",
    integer: "Integer",
    float: "Float",
    date: "Date",
    HTML: "HTML",
    options: "Options",
    showKeys: "Show keys (item sel. only)",
    taxonomyName: "Taxonomy Name",
    defaultType: "Default Type",
    displayTemplate: "Display Template",
    mergeStrategy: "Merge Strategy",
    componentPath: "Component Path",
    dependsOn: "Depends On",

    /*Restrictions*/
    required: "Required",
    minimumSelection: "Minimum Selection",
    matchPattern: "Match Pattern",
    allowDuplicate: "Allow Duplicates",

    /*Values*/
    noDatasources: "No datasources available for this control",
    editMessage: "Edit message",
    setMessage: "Set message",

    /*States Workflow*/
    setStatedTabID: "ID",
    setStatedTabState: "State",
    setStatedTabSystemProcessing: "System Processing",
    setStatedTabSelectAll: "Select All",
    false: "False",
    true: "True",

    /*Deployment Queues*/
    setQueueTabSelectAll: "Select All",
    setQueueTabID: "ID",
    setQueueTabPath: "Path",
    setQueueTabOldPath: "Old Path",
    setQueueTabEnvironment: "Environment",
    setQueueTabUser: "User",
    setQueueTabState: "State",
    setQueueTabVersion: "Version",
    setQueueTabAction: "Action",
    setQueueTabScheduledDate: "Scheduled Date",
    setQueueTabContentTypeClass: "Content Type Class",

    /*Jobs Workflow*/
    jobWorkflowTabAct: "Act",
    jobWorkflowTabJobID: "Job ID",
    jobWorkflowTabProcessName: "Process Name",
    jobWorkflowTabCreatedDate: "Created Date",
    jobWorkflowTabModifiedDate: "Modified Date",
    jobWorkflowTabSiteId: "Site Id",
    jobWorkflowTabItemsInJob: "Items<br/>in Job",
    jobWorkflowTabProperties: "Properties",
    jobWorkflowTabStatus: "Status",

    /*Loggin Levels*/
    logginLevelsTabLogger: "Logger",
    logginLevelsTabCurrentLevel: "Current Level",
    logginLevelsTabChangeLevel: "Change Level To",
    debug: "debug",
    warn: "warn",
    info: "info",
    error: "error",

    /*Configuration*/
    confTabSelectConf: "Select Configuration",
    confTabConfigurations: "Configurations",
    confTabConfDesc: "Defines this list of configurations",
    confTabContextualNavigationConf: "Contextual Navigation Configuration",
    confTabContextualNavigationConfDesc: "Defines modules on the site contextual navigation bar",
    confTabSidebarConf: "Sidebar Configuration",
    confTabSidebarConfDesc: "Defines modules on the sidebar",
    confTabEndpointsConf: "Endpoints Configuration",
    confTabEndpointsConfDesc: "Defines a list of end points available",
    confTabDevEnvironmentConf: "Dev Environment Configuration",
    confTabDevEnvironmentConfDesc: "Defines a dev environment configuration",
    confTabTargetsConf: "Targets Configuration",
    confTabTargetsConfDesc: "Defines a list of targets used for form datasource",
    confTabRTEConf: "RTE Configuration",
    confTabRTEConfDesc: "Defines Rich Text Editors configurations in form",
    confTabPreviewAssetConf: "Preview Asset Configuration",
    confTabPreviewAssetConfDesc: "Defines a list of editable assets associated with XML contents",
    confTabPreviewComponentsConf: "Preview Components Configuration",
    confTabPreviewComponentsConfDesc: "Defines a list of components that can be created dynamically in preview",
    confTabPreviewPanelConf: "Preview Panel Configuration",
    confTabconfTabPreviewPanelConfDesc: "Defines a list of tools available in preview",
    confTabPersonasConf: "Personas Configuration",
    confTabPersonasConfDesc: "Defines a list of personas available to assume in preview",
    confTabNotificationConf: "Notification Configuration",
    confTabNotificationConfDesc: "Defines a list of UI messages",
    confTabPermissionsMappings: "Permissions Mapping",
    confTabPermissionsMappingsDesc: "Defines a map of permissions and paths",
    confTabRoleMappings: "Role Mappings",
    confTabRoleMappingsDesc: "Defines a list of roles available in site",
    confTabSiteConfiguration: "Site Configuration",
    confTabSiteConfigurationDesc: "Defines the general site configuration",
    confTabSiteConf: "Site Config Tools",
    confTabSiteConfDesc: "Defines the list of admin tools available",
    confTabWorkflowConf: "Workflow Configuration",
    confTabWorkflowConfDesc: "Defines workflows available in the system",
    confCacheCleared : "Configuration cache cleared.",
    confTabTargetingConfiguration: "Targeting Configuration",
    confTabTargetingConfigurationDesc: "This file configures the targeting system of Crafter Studio to help provide Crafter Engine with fake user properties that help drive the targeting system",
    confTabEnvironmentConfiguration: "Environment Configuration",
    confTabEnvironmentConfigurationDesc: "This file configures the environments Crafter Studio can publish to",
    confTabCMISConfiguration: "CMIS Configuration",
    confTabCMISConfigurationDesc: "This files configures 0 or more CMIS-capable repositories as data-sources for content authors to pick from",
    confTabEngineSiteConfiguration: "Engine Site Configuration",
    confTabEngineSiteConfigurationDesc: "Site configuration used by Crafter Engine",
    confTabEngineSiteAppContextConfiguration: "Engine Site Application Context",
    confTabEngineSiteAppContextConfigurationDesc: "Site application context used by Crafter Engine",

    /* Image */
    constraintsError: "The uploaded file does not meet the specified width & height constraints",
    sizeError: "Image is smaller than the constraint size",
    fileNotImage: "The uploaded file is not of type image",
    loadImageError:"Unable to load the selected image. Please try again or select another image",

    /* Errors */
    error: "Error",
    errorTitle: ". Please fill every title for fields and datasources.",
    errorName: ". Please fill variable name for: ",
    contentTypeNotFound: "Component's content type not found.",
    failConfig: "Failed to load configuration.",
    noConfPathError: "No configuration path is defined.",
    clearCacheError : "Failed to clear configuration cache",
    endpointsError: "Failed to load endpoints.",
    jobsError : "Failed to load jobs.",
    cancelDeploymentError: "Failed to cancel deployment.",
    saveDateError: "Unable to save Date/Time field. Please contact your system administrator.",
    contentTypeModifiedWarn: "Content Type has been modified, are you sure you want to abandon your changes?",
    noPathSetError: "The path field of the data source {DATASOURCENAME} is not configured properly. Please contact your administrator.",

    add: "Add",
    replace: "Replace",
    delete: "Delete",
    edit: "Edit",
    createNew: "Create New",
    browseExisting: "Browse for Existing"
});

CStudioAuthoring.Messages.registerBundle("targeting", "en", {
    targeting: "Targeting",
    clear: "Clear",
    apply: "Apply",
    cancel: "Cancel",
    userProps: "User Properties"
});
