/*
 * Copyright (C) 2007-2022 Crafter Software Corporation. All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

CStudioAuthoring.Messages.registerBundle('siteDashboard', 'ko', {
  dashboardTitle: '대시 보드',

  dashboardCollapseAll: '모든 축소',
  dashboardExpandAll: '모두 확장',
  dashboardEdit: '편집',

  approvedScheduledCollapseAll: '모든 축소',

  dashletFilterPages: '페이지',
  dashletFilterComponents: '구성 요소',
  dashletFilterDocuments: '문서',
  dashletFilterAssets: '자산',
  dashletFilterAll: '모두',

  dashletGoLiveQueueTitle: '승인을 기다리고 품목',
  dashletGoLiveCollapseAll: '모두 축소',
  dashletGoLiveExpandAll: '모두 확장',
  dashletGoLiveShowInProgress: '보기 "진행중인 " 항목',
  dashletGoLiveHideInProgress: '숨기기 "진행중인 " 항목',
  dashletGoLiveColPageName: '항목 이름',
  dashletGoLiveColEdit: '편집',
  dashletGoLiveColView: '전망',
  dashletGoLiveColURL: 'URL',
  dashletGoLiveColEnvironment: '환경',
  dashletGoLiveColPublishDate: '날짜 게시',
  dashletGoLiveColLastEditedBy: '마지막 편집으로',
  dashletGoLiveColLastEditedDate: '최근 편집',
  dashletGoLivePages: '페이지 ({0})',
  dashletGoLiveComponents: '구성 요소 ({0})',
  dashletGoLiveAssets: '자산 ({0})',
  dashletGoLiveEdit: '편집',

  dashletApprovedSchedTitle: '예약 된 항목을 승인',
  dashletApprovedSchedCollapseAll: '모두 축소',
  dashletApprovedSchedExpandAll: '모두 확장',
  dashletApprovedSchedShow: '쇼',
  dashletApprovedSchedColGoLiveDate: '라이브 날짜로 이동',
  dashletApprovedSchedColEdit: '편집',
  dashletApprovedSchedColURL: 'URL',
  dashletApprovedSchedColEnvironment: '환경',
  dashletApprovedSchedColPackageId: '패키지 ID',
  dashletApprovedSchedColLastEdited: '최근 편집',

  showNumItems: '쇼',
  dashletRecentDeployTitle: '최근 발표 된',
  dashletRecentDeployCollapseAll: '모두 축소',
  dashletRecentDeployExpandAll: '모두 확장',
  dashletRecentDeployShow: '쇼',
  dashletRecentDeployColMadeLiveDateDate: '날짜 게시',
  dashletRecentDeployColEdit: '편집',
  dashletRecentDeployColURL: 'URL',
  dashletRecentDeployColEndpoint: '환경',
  dashletRecentDeployColDeployBy: '에 의해 게시',
  dashletRecentDeployColLastEdited: '최근 편집',
  dashletRecentDeployColPageName: '항목 이름',

  dashletMyRecentActivityTitle: '내 최근 활동',
  dashletMyRecentActivityCollapseAll: '모두 축소',
  dashletMyRecentActivityExpandAll: '모두 확장',
  dashletMyRecentActivityHideLiveItems: '라이브 항목 숨기기',
  dashletMyRecentActivityShowLiveItems: ', 라이브 품목',
  ddashletMyRecentActivityShow: '쇼',
  dashletMyRecentActivityColPageName: '항목 이름',
  dashletMyRecentActivityColEdit: '편집',
  dashletMyRecentActivityColURL: 'URL',
  dashletMyRecentActivityColPublishDate: '날짜 게시',
  dashletMyRecentActivityColLastEditedBy: '마지막 편집으로',
  dashletMyRecentActivityColMyLastEdit: '내 마지막 편집',

  dashletIconGuideTitle: '아이콘 가이드',
  dashletWorkflowStatesTitle: 'Workflow States',
  dashletItemTypesTitle: 'Item Types',
  dashletIconGuideNavigationPage: '탐색 페이지',
  dashletIconGuideFloatingPage: '부동 페이지',
  dashletIconGuideComponent: '구성 요소',
  dashletIconGuideDocument: '문서',
  dashletIconGuideStateNew: '게시하지 마십시오',
  dashletIconGuideStateDisabled: '사용 안 함',
  dashletIconGuideStateDeleted: '삭제',
  dashletIconGuideStateInProgress: '편집',
  dashletIconGuideStateInWorkflow: '워크 플로에서',
  dashletIconGuideStateScheduled: '예약',
  dashletIconGuideStateSystemProcessing: '처리',
  dashletIconGuideStateLocked: '편집을 위해 잠긴',
  dashletIconGuideTemplateScript: '템플릿 또는 스크립트',
  dashletIconGuideTaxonomy: '택 소노 미',
  dashletIconGuideImage: '영상',
  dashletIconGuideVideo: '비디오',
  dashletIconGuideCss: 'CSS',
  dashletIconGuideFont: 'Font',
  dashletIconGuidePdf: 'PDF',
  dashletIconGuidePowerPoint: 'MS PowerPoint',
  dashletIconGuideWord: 'MS Word',
  dashletIconGuideExcel: 'MS Excel',
  dashletIconGuideZip: 'Zip',
  dashletIconGuideGroovy: 'Groovy',
  dashletIconGuideOtherFiles: '다른 파일들'
});

CStudioAuthoring.Messages.registerBundle('contextnav', 'ko', {
  siteContent: '사이트 콘텐츠',
  sideBar: '사이드 바',

  wcmContentEdit: '편집',
  wcmContentView: '보기',
  wcmContentSubmit: '요청 게시',
  wcmContentDependencies: '종속성',
  wcmContentDelete: '삭제',
  wcmContentSubmitDelete: '요청 삭제',
  wcmContentReject: '거부',
  wcmContentSchedule: '일정',
  wcmContentApprove: '승인 및 게시',
  wcmContentDuplicate: '중복',
  wcmContentHistory: '역사',
  wcmContentPageDisabled: '이 콘텐츠는 사용할 수 없습니다',

  InProgress: '편집',
  Deleted: '삭제',
  SubmittedforDelete: '삭제를 위해 제출',
  mixedStates: '항목 (미국 혼합)',
  Submitted: '게시를 위해 제출',
  Live: '라이브',
  Scheduled: '예약',

  search: '검색',

  logout: '로그 아웃',

  networkError: '네트워크 오류. 일부 기능은 사용할 수 없습니다.',

  notification: '공고',
  noEventError: '연관된 이벤트 핸들러가 없습니다.',

  publishStatus: '게시 상태',
  idle: '게으른',
  busy: '바쁜',
  ready: '준비된',
  stopped: '중지됨',
  started: '시작',
  quickCreateEmpty:
    '빠른 작성을위한 아무 것도 구성되어 있지 않습니다. 시스템 관리자에게 문의하여 원하는 빠른 작성 컨텐츠 유형을 구성하십시오.'
});

CStudioAuthoring.Messages.registerBundle('previewTools', 'ko', {
  previewToolsTitle: '미리보기 도구',
  inContextEditing: '상황에 맞는 편집',
  pageComponents: '페이지 구성 요소',
  responsivePreview: '응답 미리보기',
  desktop: '바탕 화면',
  browser: '브라우저',
  iphone: '아이폰 5 / 아이폰 5S',
  iPad: '아이 패드',
  targeting: '타겟팅',
  translation: '번역',
  inContextEditOn: '편집 컨텍스트 내에서',
  inContextEditOff: '상황에 맞는 편집 오프',
  publishingChannel: '출판 채널',
  web: '웹',
  smartPhone: '스마트 폰',
  tablet: '태블릿',
  multiVariantTesting: '멀티 변형 테스트',
  YellowVsBlue: '홈에 파란색 마스크 대 노란색',
  yellow: '황색',
  blue: '푸른',
  FacetedVsKeyword: '키워드 대면 처리 검색',
  faceted: '면 처리',
  facetedKeyword: '면 처리 + 키워드',
  keywordOnly: '키워드 만',
  HomeRedVsBlue: '블루 버튼 VS 홈 페이지 레드',
  red: '빨간',
  catalogPageSorting: '카탈로그 페이지 정렬',
  arrivalDate: '도착 일',
  priceHightoLow: '낮은 가격순 높은 가격',
  priceLowtoHigh: '높은 낮은 가격',
  editTemplate: '템플릿 편집',
  editController: '편집 컨트롤러',
  jumpToRegion: '지역로 이동',
  dimensionsPx: '크기 (PX)',
  viewPortSize: '뷰포트 크기 (PX)',
  presets: '사전',
  custom: '관습',
  addComponent: '구성 요소 추가',
  done: '완료',
  general: '일반',
  components: '구성 요소들',
  persona: '페르소나',
  properties: '등록',
  assume: '가정',
  update: '업데이트',
  active: '활동적인',
  reportsOff: '오프 보고서',
  reportsError: '오류로 인해 보고서를 렌더링 할 수 없습니다',
  addComponent: '구성 요소 추가',
  done: '완료',
  components: '구성 요소',
  general: '일반',
  text: '본문',

  // login
  login: '로그인',
  emailUsername: '이메일 / 사용자 이름',
  password: '이메일 비밀번호',
  signIn: '로그인',
  signBackIn: '다시 로그인',
  signInContinueWorking: '계속 작업하려면 로그인하십시오',
  sessionExpireInactivity: '비활성으로 인해 세션이 만료되었습니다',
  doneSignOut: '끝났어. 로그 아웃하다.',

  search: '수색',
  publishingStatus: '게시 상태',
  users: '사용자',
  sites: '사이트',
  help: '도움',
  documentation: '선적 서류 비치',
  about: '약',
  settings: '설정',
  signOut: '로그 아웃',
  mainMenu: '기본 메뉴',

  videoProcessed: '동영상 처리 중, 처리가 완료되면 미리보기를 사용할 수 있습니다.',
  quickCreate: '빠른 만들기',
  inContextEdit: '인 - 컨텍스트 편집'
});

CStudioAuthoring.Messages.registerBundle('siteDropdown', 'ko', {
  pages: '페이지',
  Pages: '페이지',
  page: '페이지',
  components: '구성 요소들',
  Components: '구성 요소들',
  component: '구성 요소',
  staticassets: '고정 자산',
  classes: '수업',
  templates: '템플릿',
  scripts: '스크립트',
  adminConsole: '관리 콘솔',
  siteconfig: '프로젝트 구성',
  previewSync: '미리 동기화',
  syncrepo: '저장소에서 동기화',
  allSites: '모든 사이트',
  dashboard: '계기반',
  newContent: '새로운 내용',
  newFolder: '새 폴더',
  upload: '업로드',
  edit: '편집',
  view: '전망',
  changeTemplate: '변경 템플릿',
  delete: '삭제',
  cut: '절단',
  copy: '복사',
  paste: '풀',
  duplicate: '복제',
  history: '역사',
  unlock: '잠금 해제',
  noActionsAvailable: '가능한 조치가 없습니다',
  createFolder: '폴더를 만들',
  renameFolder: '폴더 이름 바꾸기',
  createTemplate: '템플릿 만들기',
  templateFilename: '템플리트의 파일 이름 제공',
  folderName: '새 폴더 이름 제공',
  createController: '컨트롤러 만들기',
  controllerFilename: '스크립트의 파일 이름을 입력하십시오.',
  bulkUploadAssets: '대량 업로드 자산',
  lastEdited: '마지막 편집',
  editedBy: '에 의해 편집 됨',
  lockedBy: '에 의해 잠김',
  status: '지위',
  scheduled: '예약',
  loading: '로드...',

  /*tooltip-Status*/
  statusDeleted: '삭제',
  statusScheduledForDelete: '삭제 예정',
  statusSubmittedForDelete: '삭제를 위해 제출',
  statusAndDisabled: '및 장애인',
  statusProcessing: '처리',
  statusInProgress: '진행 중',
  statusLive: '살고있다',
  statusAnd: '과',
  statusSubmitted: '제출',
  statusScheduled: '예약',
  statusDisabled: '장애인',
  wcmContentSubmit: '요청 게시',
  wcmContentApprove: '승인 및 게시',

  wcmContentDependencies: 'View Dependencies',

  notification: '공고',
  previewInitiated: '미리보기 서버 동기화 - 모두 시작됨.',
  syncfromRepoInitiated: 'Synchronization from Repository initiated.',

  lookUpItemError: '항목을 찾을 수 없습니다. 시스템 관리자에게 문의하십시오.',
  pathSameError: '출발지와 도착지 경로가 동일 함.',
  pageExistError: '페이지가 이미 대상에 있습니다.',

  create: '몹시 떠들어 대다',
  rename: '이름 바꾸기',
  cancel: '취소'
});

CStudioAuthoring.Messages.registerBundle('forms', 'ko', {
  styleFormatsParseError:
    'RTE `styleFormats` 구성이 잘못되었습니다: {0}. RTE 구성 styleFormats를 확인하고 유효한 JSON인지 확인하십시오. 아래에 첨부된 구성 내용:',
  new: '새로운',
  expandAll: '모두 확장',
  collapseAll: '모두 축소',
  pageName: '항목 이름',
  location: '위치',
  sectionValidation: '{0}의 {1} 필드 요구 사항은 무효',
  saveAndClose: '저장 후 닫기',
  saveAndPreview: '저장 및 미리보기',
  save: '저장',
  cancel: '취소',
  close: '닫기',
  repeatAddAnother: '또 다른 추가',
  repeatMoveUp: '위로 이동',
  repeatMoveDown: '아래로 이동',
  repeatDelete: '삭제',
  errMissingRequirements: '모든 형태의 요구 사항을 만족할 때까지 당신은 저장할 수 없습니다',
  errSaveFailed: '. 형태의 컨텐츠를 저장할 수 없습니다 다시 연락처 또는 시스템 관리자 나 시도하십시오.',
  errOnRepeat: '중계기 작동에 오류 : {0}',
  errFailedToLoadContent: '오류 내용을로드 : {0}',
  errExpectedIndexXml: '이 Index.xml 이외의 파일 이름을 기대되지 않음',
  ok: '확인',
  yes: '네',
  no: '아니',
  openType: '개방형',
  submit: '제출',
  loading: '로드&hellip;',
  viewSample: '샘플보기',
  hideSample: '숨기기 샘플',
  continueEditing: '편집을 계속',
  notification: '공고',
  previewLoaded: '미리로드 됨.',

  chooseContentType: '콘텐츠 유형 선택',
  chooseContentTypeBody: '이 섹션에서 사용할 수 있는 시작 템플릿은 다음과 같습니다.',
  chooseContentTypeLabel: '컨텐츠 타입:',
  chooseContentTypePreview: '시사:',

  cancelDialogHeader: '크래프터 스튜디오',
  cancelDialogBody: '변경 사항을 저장하지 않고이 양식을 닫습니다?',
  noContentTypes: '경로에서 콘텐츠를 사용할 수있는 콘텐츠 유형 없음:',
  noTemplatesAssoc: '페이지 관련된 템플릿 없습니다:',
  noTemplateAssocAdm:
    '이 콘텐츠 유형과 관련된 템플릿이 없습니다. 계속 함께 작업을 저장하거나 템플릿 (기본 콘텐츠 형식 속성 아래) 콘텐츠 형식을 업데이트 계속하려면 저장을 클릭합니다.',

  changeTemplateDialogTitle: '경고 : 콘텐츠 형식 변경',
  changeTemplateDialogSubTitle: '크래프터 스튜디오',
  changeTemplateDialogBody: '아래의 조작은 데이터 손실이 발생할 수 있습니다. 당신은 계속 진행 하시겠습니까?',

  bulkPublishDialogTitle: '경고 : 대량 게시',
  bulkPublishDialogBody:
    '대량 게시는 요청한 패턴과 일치하는 모든 항목을 종속성을 포함하여 강제로 게시합니다. 잠재적으로 누군가 진행중인 작업을 포함하여 모든 수정 된 항목이 </br> 계속되기 전에 게시 될 준비가되었는지 확인하십시오.',
  bulkPublish: '대량 게시',
  bulkPublishPathToPublish: '게시 경로',
  bulkPublishPublishingEnv: '출판 환경',
  bulkPublishPublish: '게시',

  historyDialogTitle: '버전 기록',
  historyDialogSubTitle: '역사에 대해 표시 :',
  historyDialogTableRowVersion: '버전 날짜 및 시간',
  historyDialogTableRowTime: '편집 시간',
  historyDialogTableRowEditBy: '편집',
  historyDialogTableRowComment: '논평',
  historyDialogRevert: '되돌리기',
  historyDialogTableRowActions: '행위',
  historyDialogLoadingWait: '로딩 중 기다려주세요&hellip;',
  historyDialogNoVersionsFound: '어떤 버전을 찾을 수 없습니다.',
  historyDialogUnable: '버전 기록을로드 할 수 없습니다.',
  historyDialogTryAgain: '다시 시도',
  historyDialogViewFileMessage: '이 버전보기',
  historyDialogCompareFileMessage: '현재에 비해',
  historyDialogRevertFileMessage: '이 버전으로 되돌리기',
  historyDialogCompare: '비교',

  deleteDialogTitle: '삭제',
  deleteDialogSubTitle:
    '선택된 항목은 하위 항목과 함께 삭제됩니다. 종속 항목을 삭제하기 전에 검토하여 링크 참조가 끊어 지도록하십시오.',
  deleteDialogSetLink: '이제"모든 것을 설정',
  deleteDialogPage: '페이지',
  deleteDialogDelete: '삭제',
  deleteDialogNow: '지금',
  deleteDialogFeedBack: '제출하기 전에 종속성 확인해야합니다',
  deleteDialogNoItemsSelected: '선택 항목이 없습니다',
  deletedTitle: '선택 삭제됨',
  deletedMessage: '선택 항목이 삭제되며 곧 삭제됩니다.',

  deleteSubmitDialogTitle: '삭제 제출',
  deleteSubmitDialogTime: '당신이 체크 된 항목을 원하는 경우 삭제할?',
  deleteSubmitEmailMe: '내 항목이 삭제 될 때 이메일을 보내주세요',
  deleteSubmitDialogAsSoon: '최대한 빨리.',

  approveDialogTitle: '게시에 대한 승인',
  approveDialogSubTitle:
    '선택한 파일이 게시됩니다. 엄격한 종속성이 자동으로 포함됩니다. 소프트 종속성은 선택 사항이며 포함 할 항목을 선택할 수 있습니다.',
  approveDialogWarning: '경고 : 승인을 위해 선택한 항목이 요청 된 다른 게시 날짜 / 시간과 함께 제출되었습니다.',
  dependenciesDialogTitle: 'Dependencies',
  dependenciesDialogSubTitle: 'Dependencies shown for:',
  dependsOn: 'Depends On',
  dependsOnMe: 'Depends On Me',
  selectDeps: 'Show content that:',
  dependenciesDialogItem: 'Item',
  approveDialogPage: '페이지',
  approveDialogOriginalSchedule: '원래 일정',
  approveDialogSubmissionComment: '제출 코멘트',
  approveDialogSelectedScheduling: '선택 항목 예약',
  approveDialogItemsLiveNow: '항목이 지금 게시되어야합니다.',
  approveDialogItemsLiveDate: '특정 날짜와 시간에 항목을 게시해야합니다',
  approveDialogPublishContent: '콘텐츠를 게시',
  approveDialogPublishingOptions: '게시 대상',
  approveDialogBroadcastUpdate: '방송 콘텐츠 업데이트',

  requestApproveDialogTitle: '게시를 요청할',
  requestApproveDialogSubTitle: '선택한 항목을 언제 게시 하시겠습니까?',
  requestApproveDialogEmailMe: '항목이 게시가 승인되면 이메일을 보내십시오.',

  itemsForPublish: '게시 할 항목',
  selectAll: '모두 선택',
  hardDependencies: '어려운 의존성',
  submissionMandatory: '제출 필수',
  softDependencies: '소프트 종속성',
  submissionOptional: '제출 옵션',
  showAllDependencies: 'S모든 종속성 표시',
  changesSelectionItems: '게시 할 항목 선택을 변경하면 "모든 종속성"을 다시 계산해야합니다.',
  loadingDependencies: '종속성로드 중입니다. 잠시만 기다려주십시오 ...',

  childItemsText: '아동 용품',
  willGetDeleted: '삭제됩니다',
  dependendtItems: '종속 품목',
  brokenItems: '참조가 깨질 것입니다',
  deleteItems: '항목 삭제',
  uploadingDepenedents: '부양 가족 업데이트 중입니다. 잠시만 기다려주십시오.',

  newContTypeDialogTitle: '콘텐츠 형식 만들기',
  newContTypeDialogDisplayLabel: '상표',
  newContTypeDialogContentTypeName: '신분증',
  newContTypeDialogType: '유형',
  newContTypeDialogPage: '페이지',
  component: '구성 요소',
  newContTypeDialogLabelMsg: '이 콘텐츠 유형 표시 라벨을 제공',
  newContTypeDialogContentTypeNamelMsg: '이 콘텐츠 유형에 대한 시스템 이름을 입력합니다',
  newContTypeDialogTypeMsg: '이 콘텐츠 유형에 대한 유형을 선택',
  contentTypeDisplayNameExists: '라벨이 이미 존재합니다.',
  contentTypeNameExists: '아이디가 이미 존재합니다.',
  contentTypeNameInvalid: '잘못된 콘텐츠 유형 ID',

  adminHelpDialogTitle: '필드 내용',

  adminKeyValDialogTitle: '값',
  adminKeyValDialogKey: '키',
  adminKeyValDialogValue: '값',
  addAnother: '또 다른 추가',

  supportedChannelsDialogLabel: '상표',
  supportedChannelsDialogName: '이름',
  supportedChannelsDialogSize: '크기',

  setStatedDialogTitle: '국가를 선택하십시오',
  setStatedDialogSetStates: '설정 미국',
  setStatedDialogSystemProcessing: '시스템 처리',

  currentPage: '현재 페이지',

  previewInitiated: '미리보기 서버 동기화 - 모두 시작됨.',
  synchronizationRepo: '저장소에서 동기화가 시작되었습니다.',

  /*Preview*/
  previewToolsTitle: '미리보기 도구',
  inContextEditing: '상황에 맞는 편집',
  pageComponents: '페이지 구성 요소',
  publishingChannel: '출판 채널',
  inContextEdit: '인 - 컨텍스트 편집',

  /*Error*/
  legacyFormNoSupported: '더 이상 지원되지 않는 레거시 양식 서버.',
  loadContentsError: '내용을로드 할 수 없습니다. 대화창을 닫고 다시 시도하십시오.',
  taxonomyError: '사용할 수있는 택 소노 미 유형이 없습니다',
  getDomainNameError: 'Service.getDomainName은 더 이상 사용되지 않습니다.',
  changeContTypeError: '콘텐츠 유형 변경 오류.',
  notImplemented: '구현되지 않음.',
  timeFormatError: '유효한 시간 형식이 아닙니다. 올바른 시간을 제공하십시오.',
  localStoreExceeded: '당신의 로컬 저장소 할당량을 초과했습니다.',
  invalidFormat: '유효한 시간 형식이 아닙니다. 올바른 시간을 제공하십시오.',
  addMoreItemsError: '더 이상 항목을 추가 할 수 없으며 항목을 제거하고 다시 시도하십시오.',
  imgReq: '이미지 설명이 필요합니다.',
  datasourceNotImageManager: '구성된 데이터 소스는 이미지 관리자가 아닙니다.',
  noDatasourceAssociated: '이 편집기와 연결된 데이터 소스가 없습니다.',
  notAComponent: ' 구성 요소가 아니거나 항목이 없습니다.',
  unableLoad: '시스템을로드 할 수 없습니다 ',
  failure: '실패',
  loadFormDefError: '양식 정의를로드하지 못했습니다.',
  loadModelError: '모델을로드하지 못했습니다.',
  controllerError: '컨트롤러가 없습니다.',
  notExist: ' 존재하지 않는다.',
  translationSubmitted: '번역이 제출되었습니다.',
  numberPerPage: '페이지 당 표시 항목에 숫자를 입력하십시오.',
  revertError: '되돌리기에 실패했습니다.',
  legacyError: '레거시 양식 서버는 더 이상 지원되지 않습니다.',
  contentTypesEmpty: '구성된 경로에서 사용할 수있는 콘텐츠 형식이 없습니다',
  componentCategoriesError: '사용할 수있는 카테고리가 없습니다',
  pluginError: '플러그인 구성에 문제가 있습니다. 다음과 같은 속성이 없습니다',
  pluginErrorSolution:
    '[사이트 구성 페이지] </a>로 이동하여 드롭 다운에서“사이트 구성 도구”를 선택하여 파일을 편집하십시오.',
  control: '제어: ',
  datasource: '데이터 소스: ',
  propertyMessage: ' 재산이 없습니다',
  propertiesMessage: '속성이 없습니다'
});

CStudioAuthoring.Messages.registerBundle('search', 'ko', {
  searchInput: '수색',
  numResults: '결과 수',
  selectAll: '모두 선택',
  filters: '필터',
  relevance: '관련성',
  asc: '오름차순',
  desc: '내림차순',
  moreRelevance: '가장 관련성이 높은 것',
  lessRelevance: '먼저 덜 관련',
  sortOrder: '정렬 순서',
  sortBy: '정렬 기준',
  name: '이름',
  images: '이미지',
  videos: '비디오',
  width: '폭',
  height: '신장',
  'content-type': '컨텐츠 타입',
  'mime-type': 'MIME 유형',
  'last-edit-date': '마지막 편집 날짜',
  size: '콘텐츠 크기',
  today: '오늘',
  'in-last-day': '마지막 날에',
  'in-last-week': '지난 주',
  'over-a-month-ago': '한 달 이상',
  'over-six-months-ago': '6 개월 이상',
  'over-a-week-ago': '1 주일 이상',
  'over-a-year-ago': '1 년이 넘었습니다.',
  paginationFirst: '먼저',
  paginationPrev: '예전의',
  paginationNext: '다음 것',
  paginationLast: '마지막',
  seeMore: '더보기',
  seeLess: '덜보기',
  under: '아래에',
  above: '위',
  errorMessage: '검색을 완료하는 중에 문제가 발생했습니다. 문제가 지속되면 관리자에게 문의하십시오.',
  clear: '명확한',
  apply: '대다'
});

CStudioAuthoring.Messages.registerBundle('browse', 'ko', {
  labelUrl: 'URL',
  labelType: '유형',
  labelAddClose: '추가 및 닫기',
  labelAddLink: '링크 추가',
  labelClone: '클론',
  selectAll: '모두 선택',
  clearAll: '선택 지우기',
  uploadLabel: '업로드',
  notification: '공고',
  lookUpChildError: '검색을 위해 하위 양식 콜백을 조회 할 수 없음 : ',
  lookUpParentError: '검색을 위해 상위 컨텍스트를 조회 할 수 없음 : ',
  loading: '로딩',
  noBrowseResults: 'There are no files at this path.',
  noSearchResults: 'There are no results.',
  showMore: '자세히보기',
  400: '잘못된 CMIS 매개 변수 잘못된 CMIS 데이터 소스 구성 (호스트 이름, 포트 번호 등)은 사이트 관리자에게 문의하십시오.',
  401: 'CMIS 무단 : CMIS 데이터 소스 구성에서 사용자 이름이나 비밀번호가 잘못되었습니다. 사이트 관리자에게 문의하십시오.',
  404: 'CMIS 경로를 찾을 수 없습니다.',
  408: 'CMIS 타임 아웃.',
  500: '인터넷 서버 오류.',
  503: 'CMIS를 사용할 수 없습니다.'
});

CStudioAuthoring.Messages.registerBundle('contentTypes', 'ko', {
  contenttypes: '콘텐츠 형식',
  bulkoperations: '대량 작업',
  workflowjobs: '워크 플로 작업',
  workflowstates: '워크 플로우 미국',
  logginglevels: '로깅 수준',
  logconsole: '로그인 콘솔',
  publishing: '출판',
  status: '지위',
  audit: '심사',
  groups: '여러 떼',
  contentTypes: '콘텐츠 형식',
  configuration: '구성',
  workflowJobs: '워크 플로 작업',
  workflowStates: '워크 플로우 미국',
  loggingLevels: '로깅 수준',
  logConsole: '로그인 콘솔',
  previewsync: '미리보기 동기화',
  syncfromrepository: '저장소에서 동기화',
  label: '콘텐츠 형식',
  openExistingType: '열기 기존 유형',
  createNewType: '새로운 유형 만들기',
  save: '저장',
  cancel: '취소',
  create: '몹시 떠들어 대다',
  close: '닫기',
  saved: '저장',
  clearVal: '지우기 값',
  saveFailed: '저장 실패',
  formSection: '양식 섹션',
  repeatingGroup: '반복 그룹',
  minOccurs: '최소 발생 수',
  maxOccurs: '최대 발생 수',
  formBasics: '양식 기본 사항',
  formTitle: '이름',
  description: '기술',
  objectType: '개체 유형',
  contentType: '컨텐츠 유형',
  datasourceBasics: '데이터 소스 기본 사항',
  title: '이름',
  name: '이름',
  properties: '등록',
  sectionBasics: '섹션 기본 사항',
  variableName: '이름 / 변수 이름',
  iceGroup: 'ICE 그룹',
  fieldBasics: '필드의 기본 사항',
  defaultValue: '기본값',
  help: '도와주세요',
  constraints: '제약',
  propertiesExplorer: '등록 탐색기',
  controls: '컨트롤',
  datasources: '데이터 소스',
  defaultOpen: '기본 열기',
  showInNav: '탐색에 표시',
  descriptorMapper: '매퍼',
  previewImage: 'Preview Image ',
  config: 'Configuration',
  controller: 'Controller',
  notification: '공고',
  deploymentCanceled: '배포 항목이 취소되었습니다.',

  createTemplate: '템플릿 만들기',
  templateFilename: '템플리트의 파일 이름 제공',

  /*Controls*/
  textArea: '텍스트 영역',
  rte: '서식있는 텍스트 편집기s',
  input: '입력',
  numericInput: '숫자 입력',
  uuid: 'UUID',
  dropdown: '쓰러지 다',
  dateTime: '날짜 시간',
  time: '시간',
  checkBox: '확인란',
  groupedCheckboxes: '그룹화 확인란',
  itemSelector: '항목 선택기',
  image: '영상',
  video: '비디오',
  label: '상표',
  pageOrder: '페이지 순서',
  fileName: '파일 이름',
  autoFilename: '자동 파일 이름',
  forceHTTPS: '포스 HTTPS',
  disabled: '장애인',
  flash: '플래시',
  internalName: '내부 이름',
  basicContentTypeProp: '기본 콘텐츠 형식 등록',
  publishStarted: '게시 프로세스가 시작되었습니다',

  /*Datasources */
  childContent: '자식 내용',
  embeddedContent: '임베디드 컨텐츠',
  imageUploadedDesktop: '이미지 바탕 화면에서 업로드',
  WebDAVUploadImage: 'WebDav 저장소에 업로드 된 이미지',
  WebDAVUploadVideo: 'WebDav 저장소에 업로드 된 비디오',
  imageWebDavRepository: 'WebDav 저장소의 이미지',
  videoWebDavRepository: 'WebDav 저장소의 비디오',
  fileWebDavRepository: 'WebDav 저장소의 파일',
  fileUploadedWebDavRepository: 'WebDav 저장소에 업로드 된 파일',
  S3UploadImage: 'S3 저장소에 업로드 된 이미지',
  S3UploadVideo: 'S3 저장소에 업로드 된 비디오',
  imageS3Repository: 'S3 저장소의 이미지',
  videoS3Repository: 'S3 저장소의 비디오',
  videos3Transcoding: 'S3 저장소에서 비디오 트랜스 코딩',
  fileS3Repository: 'S3 저장소의 파일',
  fileUploadedS3Repository: 'S3 저장소에 업로드 된 파일',
  DAMImage: 'DAM 이미지 플리커 (Flickr)',
  fileUploadedDesktop: '파일 바탕 화면에서 업로드',
  flashUploadedDesktop: '플래시 바탕 화면에서 업로드',
  videoUploadedDesktop: '비디오 바탕 화면에서 업로드',
  videoBrowse: '리포지토리의 비디오',
  videoCMISRepository: 'CMIS 저장소 비디오',
  staticKeyValuePairs: '정적 키 값 쌍',
  configuredListOfPairs: '쌍의 구성 목록',
  fileBrowse: '찾아보기를 파일',
  hubspotForms: '허브 스팟 양식',
  imageFromRepository: '저장소에서 이미지',
  imageFromCMISRepository: 'CMIS 저장소의 이미지',
  CMISRepository: 'CMIS 저장소의 파일',
  CMISUpload: 'CMIS 저장소에 업로드 된 파일',
  CMISUploadImage: 'CMIS 저장소에 업로드 된 이미지',
  CMISUploadVideo: 'CMIS 저장소에 업로드 된 비디오',
  salesforceCampaigns: '세일즈 포스 캠페인',
  treeContent: '트리 내용',

  /*Properties*/
  Size: '크기',
  maxLength: '최대 길이s',
  width: '폭',
  height: '신장',
  autoGrow: '자동 성장',
  allowResize: '크기 조정 허용',
  forceRootBlockP: '강제 루트 블록 p 태그',
  forcePNewLines: '강제 p는 신규 라인 태그',
  forceBRNewLines: '포스 카에 새로운 라인',
  requireImageAlt: '이미지 Alt 키 태그를 필요',
  supportedChannels: '지원 채널',
  RTEConfiguration: 'RTE 구성',
  imageManager: '이미지 관리자',
  videoManager: '비디오 매니저',
  showDate: '쇼 날짜',
  showTime: '쇼 타임',
  showClear: '표시 지우기 값',
  setNowLink: '이제 링크 설정',
  populated: '인구',
  allowPastDate: '과거 날짜 허용',
  populateExpression: '',
  readonly: '읽기 전용',
  readonlyOnEdit: '편집에 읽기 전용',
  datasource: '데이터 소스',
  showSelectAll: '쇼는 "모두 선택"',
  allowEmptyValue: '빈 값을 허용',
  thumbnailWidth: '미리보기 폭',
  thumbnailHeight: '미리보기 높이',
  displaySize: '디스플레이 크기',
  text: '본문',
  minSize: '최소 크기',
  maxSize: '최대 크기',
  itemManager: '항목 관리자',
  disableFlatteningSearch: '검색 편평 해제',
  singleValueFilename: '단일 값의 파일 이름을 사용 (이전 버전과 호환)',
  columns: '열',
  rows: '행',
  dataType: '데이터 형식',
  listName: '목록 이름',
  repositoryId: '식별 저장소',
  repositoryPath: '저장소 경로',
  studioPath: '스튜디오 경로',
  browsePath: '찾기 경로',
  allowedOperations: '허용 작업',
  clone: '복제',
  link: '링크',
  cloneAndLink: '복제 및 링크',
  string: '현',
  integer: '정수',
  float: '플로트',
  date: '날짜',
  HTML: 'HTML',
  options: '옵션',
  showKeys: '보기 키 (항목 전용)',
  taxonomyName: '분류 이름',
  defaultType: '기본 유형',
  displayTemplate: '디스플레이 템플릿',
  noTemplateRequired: '템플릿 필요 없음',
  mergeStrategy: '전략을 병합',
  profileId: '프로필 ID',
  path: '통로',
  type: '유형',
  quickCreate: '빠른 만들기',
  showQuickCreate: '빠른 만들기에 표시',
  destinationPath: '대상 경로 패턴',
  inputProfileId: '입력 프로파일 ID',
  outputProfileId: '출력 프로필 ID',
  postfixes: '포스트 픽스',
  enableCreateNew: '쇼 새로 만들기',
  enableBrowseExisting: '쇼 기존 항목 찾아보기',
  enableSearchExisting: '쇼 기존 검색',
  useSearch: '검색 사용',

  /*Restrictions*/
  required: '필요',
  minimumSelection: '최소 선택',
  matchPattern: '경기 패턴',
  allowDuplicate: '중복 허용',

  /*Values*/
  noDatasources: '이 컨트롤에 사용 가능한 데이터 소스가 없습니다',
  editMessage: '편집 메시지',
  setMessage: '설정 메시지',

  /*States Workflow*/
  setStatedTabID: 'ID',
  setStatedTabState: '상태x',
  setStatedTabSystemProcessing: '시스템 처리',
  setStatedTabSelectAll: '모두 선택',
  false: '그릇된',
  true: '참된',

  /*Jobs Workflow*/
  jobWorkflowTabAct: '행위',
  jobWorkflowTabJobID: '작업 확인',
  jobWorkflowTabProcessName: '프로세스 이름',
  jobWorkflowTabCreatedDate: '만든 날짜',
  jobWorkflowTabModifiedDate: '수정 한 날짜',
  jobWorkflowTabSiteId: '사이트 아이디',
  jobWorkflowTabItemsInJob: '작업의 항목',
  jobWorkflowTabProperties: '등록',
  jobWorkflowTabStatus: '지위',

  /*Loggin Levels*/
  logginLevelsTabLogger: '로거',
  logginLevelsTabCurrentLevel: '현재 수준',
  logginLevelsTabChangeLevel: '변경 수준',
  debug: '디버그',
  warn: '경고',
  info: '정보',
  error: '오류',

  /*Configuration*/
  confTabSelectConf: '구성을 선택합니다',
  confTabConfigurations: '구성',
  confTabConfDesc: '구성의 목록을 정의합니다',
  confTabContextualNavigationConf: '콘텐츠 탐색 구성',
  confTabContextualNavigationConfDesc: '사이트 콘텐츠의 탐색 모음에서 모듈을 정의합니다',
  confTabSiteDropdownConf: '사이트 구성 드롭 다운',
  confTabSiteDropdownConfDesc: '사이트 드롭 다운 표시 줄에 모듈을 정의합니다',
  confTabEndpointsConf: '엔드 포인트 구성',
  confTabEndpointsConfDesc: '엔드 포인트의리스트가 정의 가능한',
  confTabDevEnvironmentConf: '데브 환경 구성',
  confTabDevEnvironmentConfDesc: '개발 환경의 구성을 정의',
  confTabTargetsConf: '대상 구성',
  confTabTargetsConfDesc: '대상 목록 양식 데이터 소스에 사용되는 정의합니다',
  confTabRTEConf: 'RTE 구성',
  confTabRTEConfDesc: '서식있는 텍스트 편집기는 형태로 구성을 정의',
  confTabRTEtMCE5Conf: 'RTE (TinyMCE 5) 구성',
  confTabRTEtMCE5Desc: '서식있는 텍스트 편집기는 형태로 구성을 정의',
  confTabCodeEditorConf: '코드 편집기 구성',
  confTabCodeEditorConfDesc: '코드 편집기 구성을 정의합니다',
  confTabPreviewAssetConf: '자산 미리 구성',
  confTabPreviewAssetConfDesc: 'XML 컨텐츠와 연관된 편집 자산 목록을 정의',
  confTabPreviewComponentsConf: '구성 요소 구성 미리보기',
  confTabPreviewComponentsConfDesc: '프리뷰를 동적으로 생성 할 수있는 구성 요소의 목록을 정의',
  confTabPreviewPanelConf: '미리보기 패널 구성',
  confTabconfTabPreviewPanelConfDesc: '미리보기에서 사용할 수있는 도구의 목록을 정의',
  confTabPersonasConf: '사람 구성',
  confTabPersonasConfDesc: '사람들은 미리보기에서 가정 할 수 사람들의 목록을 정의합니다',
  confTabNotificationConf: '알림 구성',
  confTabNotificationConfDesc: 'UI 메시지의 목록을 정의',
  confTabPermissionsMappings: '권한 매핑',
  confTabPermissionsMappingsDesc: '권한 및 경로 맵을 정의',
  confTabRoleMappings: '역할 매핑',
  confTabRoleMappingsDesc: '사이트에서 사용할 수있는 역할의 목록을 정의합니다',
  confTabSiteConfiguration: '사이트 구성',
  confTabSiteConfigurationDesc: '일반 사이트 구성을 정의',
  confTabSiteConf: '콘텐츠 유형 편집기 구성',
  confTabSiteConfDesc: '콘텐츠 유형 편집에 사용할 수 있는 컨트롤 및 데이터 소스 정의',
  confTabWorkflowConf: '워크 플로우 구성',
  confTabWorkflowConfDesc: '시스템에서 사용할 수있는 워크 플로우를 정의',
  confCacheCleared: '구성 캐시가 지워졌습니다.',
  confTabTargetingConfiguration: '타겟팅 구성',
  confTabTargetingConfigurationDesc:
    '이 파일은 Crafter Studio의 타겟팅 시스템을 구성하여 Crafter Engine에 타겟팅 시스템을 구동하는 데 도움이되는 가짜 사용자 속성을 제공합니다',
  confTabEnvironmentConfiguration: '환경 구성',
  confTabEnvironmentConfigurationDesc: '이 파일은 Crafter Studio가 게시 할 수있는 환경을 구성합니다',
  confTabCMISConfiguration: 'CMIS 구성',
  confTabCMISConfigurationDesc:
    '이 파일은 컨텐트 작성자가 선택할 수있는 0 이상의 CMIS 가능 리포지토리를 데이터 소스로 구성합니다',
  confTabTranslationConf: '번역 구성',
  confTabTranslationConfDesc: '지원되는 언어 및 해결 방법을 정의합니다',
  confTabSitePolicyConf: '사이트 정책 구성',
  confTabSitePolicyConfDesc: '콘텐츠 작업의 유효성을 검사하는 정책을 정의합니다.',
  confTabUiConf: '사용자 인터페이스 구성',
  confTabUiConfDesc: '사용자 인터페이스에 표시되는 위젯을 정의합니다.',
  confTabMimeTypes: 'Mime 유형',
  confTabMimeTypesDesc: '이 파일은이 사이트 / 청사진에 대한 MIME 유형 아이콘 재정의를 구성합니다.',
  confTabEngineUrlRewriteConf: '엔진 URL 재 작성 구성 (XML 스타일)',
  confTabEngineUrlRewriteConfDesc: '이 파일은 Crafter Engine에서 사용하는 사이트 속성을 구성합니다.',
  confTabEngineUrlRewriteConfPreview: '엔진 URL 재 작성 구성 (XML 스타일) - 시사',
  confTabEngineUrlRewriteConfStaging: '엔진 URL 재 작성 구성 (XML 스타일) - 각색',
  confTabEngineUrlRewriteConfLive: '엔진 URL 재 작성 구성 (XML 스타일) - 라이브',
  confTabDependencyResolverConf: '종속성 해결 프로그램 구성',
  confTabDependencyResolverConfDesc: '이 파일은 Crafter가 종속성으로 간주하는 파일 경로와 추출 방법을 구성합니다.',
  confTabAWSProfiles: 'AWS 프로필',
  confTabAWSProfilesDesc: 'AWS 프로필 구성 파일.',
  confTabBoxProfiles: '박스 프로파일',
  confTabBoxProfilesDesc: '박스 프로파일 구성 파일.',
  confTabWebDAVProfiles: 'WebDAV 프로필',
  confTabWebDAVProfilesDesc: 'WebDAV 프로필 구성 파일.',
  confTabAssetProcessing: '자산 처리',
  confTabAssetProcessingDesc: '자산 처리 구성 파일.',
  confTabBlobStores: 'Blob 저장소',
  confTabBlobStoresDesc: 'Blob은 구성 파일을 저장합니다.',
  confTabProxyConfig: '프록시 구성',
  confTabProxyConfigDesc: '이 파일은 미리보기를 위해 프록시 서버를 구성합니다.',
  confTabEngineSiteConfiguration: '엔진 사이트 구성',
  confTabEngineSiteConfigurationDesc: 'Crafter Engine에서 사용하는 사이트 구성',
  confTabEngineSiteConfigurationPreview: '엔진 사이트 구성 - 시사',
  confTabEngineSiteConfigurationStaging: '엔진 사이트 구성 - 각색',
  confTabEngineSiteConfigurationLive: '엔진 사이트 구성 - 라이브',
  confTabEngineSiteAppContextConfiguration: '엔진 사이트 애플리케이션 컨텍스트',
  confTabEngineSiteAppContextConfigurationDesc: 'Crafter Engine에서 사용하는 사이트 애플리케이션 컨텍스트',
  confTabEngineSiteAppContextConfigurationPreview: '엔진 사이트 애플리케이션 컨텍스트 - 시사',
  confTabEngineSiteAppContextConfigurationStaging: '엔진 사이트 애플리케이션 컨텍스트 - 라이브',
  confTabEngineSiteAppContextConfigurationLive: '엔진 사이트 애플리케이션 컨텍스트 - 라이브',

  /*Postfixes*/
  iDescription: '정수의 경우',
  sDescription: '문자열의 경우',
  lDescription: '긴 정수의 경우',
  tDescription: '여러 단어 또는 토큰의 경우',
  bDescription: '부울의 경우 (true 또는 false)',
  fDescription: '부동 소수점 숫자',
  dDescription: '긴 부동 소수점의 경우',
  dtDescription: 'ISO 8601 날짜 형식의 날짜',
  toDescription: 'HH 시간 : mm : ss 형식',
  htmlDescription: 'HTML 태그가있는 텍스트의 경우',
  oDescription: '오브젝트 용',
  enDescription: '여러 단어 또는 토큰의 경우',
  txtDescription: '여러 단어 또는 토큰의 경우',

  /* Errors */
  error: '오류',
  errorTitle: '. 필드와 데이터 소스에 대한 모든 제목을 입력 해주세요.',
  postfixError: '모델 필드에는 각각의 데이터 유형 후위가 필요합니다. ',
  optionsPostfixError: '옵션은 ',
  optionPostfixError: '옵션은 ',
  andPostfixError: '과',
  errorName: '. 대한 변수 이름을 기입하십시오: ',
  contentTypeNotFound: '구성 요소의 콘텐츠 형식을 찾을 수 없습니다.',
  failConfig: '구성을로드하지 못했습니다.',
  noConfPathError: '구성 경로가 정의되지 않았습니다.',
  endpointsError: '엔드 포인트로드 실패.',
  jobsError: '작업을로드하지 못했습니다.',
  cancelDeploymentError: '배포를 취소하지 못했습니다.',
  saveDateError: '날짜 / 시간 필드를 저장할 수 없습니다. 시스템 관리자에게 문의하십시오.',
  contentTypeModifiedWarn: '콘텐츠 유형이 수정되었습니다. 변경 사항을 취소하시겠습니까?',
  noPathSetError: '{DATASOURCENAME} 데이터 소스의 경로 필드가 올바르게 구성되지 않았습니다. 관리자에게 문의하십시오.',

  add: '더하다',
  replace: '바꾸다',
  delete: '지우다',
  edit: '편집하다',
  createNew: '새로 만들기',
  browseExisting: '기존 항목 찾아보기',
  searchExisting: '기존 검색',

  /*help popover*/
  pattern: '무늬',
  objectIdPattern: 'GUID를 삽입합니다.',
  yearPattern: '현재 연도 (4 자리 연도)를 삽입합니다.',
  monthPattern: '현재 달 (2 자리 숫자의 달)을 삽입합니다.',
  yyyyPattern: '현재 연도 (4 자리 연도)를 삽입합니다.',
  mmPattern: '현재 달 (2 자리 숫자의 달)을 삽입합니다.',
  ddPattern: '현재 날짜 (2 자리 날짜)를 삽입합니다.'
});

CStudioAuthoring.Messages.registerBundle('targeting', 'ko', {
  targeting: '타겟팅',
  clear: '명확한',
  apply: '대다',
  cancel: '취소',
  userProps: '사용자 속성'
});

CStudioAuthoring.Messages.registerBundle('dialogs', 'ko', {
  upload: '업로드',
  uploadSelect: '업로드 할 파일을 선택하십시오.',
  file: '파일',
  chooseFile: '파일을 선택',
  noFileChosen: '선택된 파일 없음',
  uploadBtn: '업로드',
  cancelBtn: '취소',
  uploading: '업로드 중'
});
